replicaCount: 1

image:
  repository: 172.31.63.178:30006/coveros/codeveros-auth-service
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
