replicaCount: 1

image:
  repository: 172.31.63.178:30006/coveros/codeveros-ui
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  nodePort:

config:
  enabled: false
  data: {}

apiUrl: /api

ingress:
  annotations: {}
  enabled: false
  host: ""
  path: "/"
  tlsSecretName: ""
