replicaCount: 1

image:
  repository: 172.31.63.178:30006/coveros/codeveros-gateway
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

authServiceNameOverride: ""
userServiceNameOverride: ""
trainingServiceNameOverride: ""

service:
  type: ClusterIP
  port: 8080

authServiceName: "codeveros-auth-service"
trainingServiceName: "codeveros-training-service"
userServiceName: "codeveros-user-service"

ingress:
  annotations: {}
  enabled: false
  host: ""
  path: "/api"
  tlsSecretName: ""
